# Generated by Django 2.0.5 on 2018-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreact',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='photoreact',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
