# Generated by Django 2.0.6 on 2018-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180603_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreact',
            name='latitud',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='photoreact',
            name='longitud',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
    ]
