# Generated by Django 2.0.6 on 2018-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180607_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreact',
            name='photo_react',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
