# Generated by Django 2.0.6 on 2018-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20181002_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoalmacen',
            name='precio_costo_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='precio_venta_unitario',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
